AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SubnetID:
    Type: String
    Default: subnet-1195677a
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: deployment-hit-cluster
  RedisLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: deployment-web-log-group
  WebLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: deployment-redis-log-group
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: deployment-hit-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ContainerSecurityGroup
      GroupDescription: Security group for NGINX container
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  JenContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: JenContainerSecurityGroup
      GroupDescription: Security group for NGINX container
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: deployment-hit-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: nginx
          Image: nginx
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref WebLogGroup
              awslogs-stream-prefix: ecs
        # - Name: redis
        #   Image: redis
        #   Essential: true
        #   PortMappings:
        #     - ContainerPort: 6379
        #   LogConfiguration:
        #     LogDriver: awslogs
        #     Options:
        #       awslogs-region: !Ref AWS::Region
        #       awslogs-group: !Ref RedisLogGroup
        #       awslogs-stream-prefix: ecs
        # - Name: web
        #   Image: devopsjuly22017/web
        #   PortMappings:
        #     - ContainerPort: 5000
        #   LogConfiguration:
        #     LogDriver: awslogs
        #     Options:
        #       awslogs-region: !Ref AWS::Region
        #       awslogs-group: !Ref WebLogGroup
        #       awslogs-stream-prefix: ecs
      RequiresCompatibilities:
        - EC2
        - FARGATE
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: deployment-hit-service
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetID
          SecurityGroups:
            - !GetAtt ContainerSecurityGroup.GroupId

  JenTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: deployment-jen-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: nginx
          Image: jenkins/jenkins:lts
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref WebLogGroup
              awslogs-stream-prefix: ecs
      RequiresCompatibilities:
        - EC2
        - FARGATE
  JenService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: deployment-jen-service
      Cluster: !Ref Cluster
      TaskDefinition: !Ref JenTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetID
          SecurityGroups:
            - !GetAtt ContainerSecurityGroup.GroupId
